2024-01-05 22:57:40,691 INFO    MainThread:27515 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-05 22:57:40,691 INFO    MainThread:27515 [wandb_setup.py:_flush():76] Configure stats pid to 27515
2024-01-05 22:57:40,691 INFO    MainThread:27515 [wandb_setup.py:_flush():76] Loading settings from /Users/cosmin/.config/wandb/settings
2024-01-05 22:57:40,691 INFO    MainThread:27515 [wandb_setup.py:_flush():76] Loading settings from /Users/cosmin/Dev/Projects/CV/lab5/wandb/settings
2024-01-05 22:57:40,691 INFO    MainThread:27515 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-05 22:57:40,692 INFO    MainThread:27515 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-01-05 22:57:40,692 INFO    MainThread:27515 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-05 22:57:40,692 ERROR   MainThread:27515 [wandb_setup.py:_flush():76] error
Traceback (most recent call last):
  File "/Users/cosmin/Dev/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1166, in init
    wi.setup(kwargs)
  File "/Users/cosmin/Dev/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 306, in setup
    wandb_login._login(
  File "/Users/cosmin/Dev/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_login.py", line 298, in _login
    wlogin.prompt_api_key()
  File "/Users/cosmin/Dev/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_login.py", line 221, in prompt_api_key
    key, status = self._prompt_api_key()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cosmin/Dev/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_login.py", line 201, in _prompt_api_key
    key = apikey.prompt_api_key(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cosmin/Dev/.venv/lib/python3.11/site-packages/wandb/sdk/lib/apikey.py", line 144, in prompt_api_key
    key = input_callback(api_ask).strip()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cosmin/Dev/.venv/lib/python3.11/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/Users/cosmin/Dev/.venv/lib/python3.11/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort
2024-01-05 22:57:40,692 INFO    MainThread:27515 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-01-05 22:57:40,692 INFO    MainThread:27515 [wandb_init.py:_log_setup():524] Logging user logs to /Users/cosmin/Dev/Projects/CV/lab5/wandb/run-20240105_225740-9ax176q1/logs/debug.log
2024-01-05 22:57:40,692 INFO    MainThread:27515 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/cosmin/Dev/Projects/CV/lab5/wandb/run-20240105_225740-9ax176q1/logs/debug-internal.log
2024-01-05 22:57:40,692 INFO    MainThread:27515 [wandb_init.py:init():564] calling init triggers
2024-01-05 22:57:40,693 INFO    MainThread:27515 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-01-05 22:57:40,693 INFO    MainThread:27515 [wandb_init.py:init():589] re-initializing run, found existing run on stack: aodrf8eo
2024-01-05 22:57:40,695 INFO    MainThread:27515 [wandb_run.py:_finish():1962] finishing run deepsmeag/Lab5/aodrf8eo
2024-01-05 22:57:40,695 ERROR   MainThread:27515 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-01-05 22:57:40,695 INFO    MainThread:27515 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-05 22:57:40,695 INFO    MainThread:27515 [wandb_init.py:_jupyter_teardown():452] cleaning up jupyter logic
2024-01-05 22:57:40,696 INFO    MainThread:27515 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-01-05 22:57:40,696 INFO    MainThread:27515 [wandb_run.py:_restore():2185] restore
2024-01-05 22:57:40,696 INFO    MainThread:27515 [wandb_run.py:_restore():2191] restore done
2024-01-05 22:57:48,627 INFO    MainThread:27515 [wandb_run.py:_footer_history_summary_info():3837] rendering history
2024-01-05 22:57:48,627 INFO    MainThread:27515 [wandb_run.py:_footer_history_summary_info():3869] rendering summary
2024-01-05 22:57:48,636 INFO    MainThread:27515 [wandb_run.py:_footer_sync_info():3796] logging synced files
2024-01-05 22:57:48,849 INFO    MainThread:27515 [wandb_init.py:init():614] starting backend
2024-01-05 22:57:48,849 INFO    MainThread:27515 [wandb_init.py:init():618] setting up manager
2024-01-05 22:57:48,850 INFO    MainThread:27515 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-01-05 22:57:48,851 INFO    MainThread:27515 [wandb_init.py:init():624] backend started and connected
2024-01-05 22:57:48,853 INFO    MainThread:27515 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-01-05 22:57:48,853 INFO    MainThread:27515 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-01-05 22:57:48,853 INFO    MainThread:27515 [wandb_init.py:init():716] updated telemetry
2024-01-05 22:57:48,853 INFO    MainThread:27515 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-01-05 22:57:50,174 INFO    MainThread:27515 [wandb_run.py:_on_init():2254] communicating current version
2024-01-05 22:57:50,404 INFO    MainThread:27515 [wandb_run.py:_on_init():2263] got version response 
2024-01-05 22:57:50,405 INFO    MainThread:27515 [wandb_init.py:init():800] starting run threads in backend
2024-01-05 22:57:50,420 INFO    MainThread:27515 [wandb_run.py:_console_start():2233] atexit reg
2024-01-05 22:57:50,421 INFO    MainThread:27515 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-01-05 22:57:50,421 INFO    MainThread:27515 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-01-05 22:57:50,421 INFO    MainThread:27515 [wandb_run.py:_redirect():2178] Redirects installed.
2024-01-05 22:57:50,421 INFO    MainThread:27515 [wandb_init.py:init():841] run started, returning control to user process
2024-01-05 23:00:16,973 INFO    MainThread:27515 [wandb_run.py:_finish():1962] finishing run deepsmeag/Lab5/9ax176q1
2024-01-05 23:00:16,973 INFO    MainThread:27515 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-01-05 23:00:16,974 INFO    MainThread:27515 [wandb_run.py:_restore():2185] restore
2024-01-05 23:00:16,974 INFO    MainThread:27515 [wandb_run.py:_restore():2191] restore done
2024-01-05 23:00:26,535 INFO    MainThread:27515 [wandb_run.py:_footer_history_summary_info():3837] rendering history
2024-01-05 23:00:26,536 INFO    MainThread:27515 [wandb_run.py:_footer_history_summary_info():3869] rendering summary
2024-01-05 23:00:26,541 INFO    MainThread:27515 [wandb_run.py:_footer_sync_info():3796] logging synced files
